development:
  adapter: postgresql
  encoding: utf8
  database: TedKwasnik_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: TedKwasnik_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: TedKwasnik_production
  pool: 5
  username:
  password:
