development:
    adapter: postgis
    encoding: unicode
    database: <%= ENV["RDS_DB_NAME"] %>
    username: <%= ENV["RDS_USERNAME"] %>
    password: <%= ENV["RDS_PASSWORD"] %>
    host: <%= ENV["RDS_HOSTNAME"] %>
    port: <%= ENV["RDS_PORT"] %>
    pool: 5

test:
  adapter: postgis
  encoding: utf8
  database: TedKwasnik_test
  pool: 5
  username:
  password:

production:
    adapter: postgis
    encoding: unicode
    database: <%= ENV["RDS_DB_NAME"] %>
    username: <%= ENV["RDS_USERNAME"] %>
    password: <%= ENV["RDS_PASSWORD"] %>
    host: <%= ENV["RDS_HOSTNAME"] %>
    port: <%= ENV["RDS_PORT"] %>
    pool: 5
